#!/usr/bin/env bash

source ./common/create_terminologies.sh
source ./common/contraventions.sh
source ./common/print_types.sh

declare contraventionFound=false

directory=${1}

for file in "$directory"/*; do
    for pattern in "${!ERROR_TERMINOLOGIES[@]}"; do
        find_error_contraventions $file $pattern
    done
done

for file in "$directory"/*; do
    for pattern in "${!WARNING_TERMINOLOGIES[@]}"; do
        find_warning_contraventions $file $pattern
    done
done

if $contraventionFound ; then 
    exit 1
fi
