#!/usr/bin/env bash

SCRIPT_PATH=$(dirname `which $0`)

source $SCRIPT_PATH/common/create_terminologies.sh
source $SCRIPT_PATH/common/contraventions.sh
source $SCRIPT_PATH/common/print_types.sh

declare contraventionFound=false
export TERM=xterm

directory=${1}

for file in "$directory"/*; do
    for pattern in "${!ERROR_TERMINOLOGIES[@]}"; do
        find_error_contraventions $file $pattern
    done
done

for file in "$directory"/*; do
    for pattern in "${!WARNING_TERMINOLOGIES[@]}"; do
        find_warning_contraventions $file $pattern
    done
done

if $contraventionFound ; then 
    exit 1
fi
